import {test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {resolve} from 'node:path';import {mkdtempSync,mkdirSync} from 'node:fs';
import {WebSocket} from 'ws';
test('HTTP smoke: loopback API, locked research, tokens, origin policy and consent',async()=>{
 mkdirSync('.runtime/tests',{recursive:true});const dir=mkdtempSync(resolve('.runtime/tests/http-'));const token='synthetic-test-token-not-a-real-credential';
 const child=spawn(process.execPath,['--import','tsx','src/server.ts','--demo'],{cwd:process.cwd(),env:{...process.env,DATA_PATH:`${dir}/test.sqlite`,RESEARCHER_TOKEN:token},stdio:['ignore','pipe','pipe']});
 try{
  await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('server_start_timeout')),5000);child.stdout.on('data',chunk=>{if(chunk.toString().includes('Ruang Akses:')){clearTimeout(timeout);resolve();}});child.on('exit',code=>{clearTimeout(timeout);reject(Error(`server exited ${code}`));});child.on('error',reject);});
  const base='http://127.0.0.1:3050';const health=await (await fetch(`${base}/api/readiness`)).json() as any;assert.equal(health.demo,true);assert.equal(health.study_enabled,false);
  assert.equal((await fetch(`${base}/study`)).status,200);
  assert.equal((await fetch(`${base}/api/research/results`)).status,401);
  assert.equal((await fetch(`${base}/api/readiness`,{headers:{Origin:'https://attacker.example'}})).status,403);
  assert.equal((await fetch(`${base}/task/unknown/`)).status,403);
  const created=await fetch(`${base}/api/sessions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'TEST',mode:'demo',slot:0,request_id:crypto.randomUUID()})});assert.equal(created.status,201);const session=await created.json() as any;
  const rejected=await fetch(`${base}/api/consent`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session_token}`},body:JSON.stringify({accepted:false,adult:true,version:'demo-v1',request_id:crypto.randomUUID()})});assert.equal(rejected.status,200);assert.equal((await rejected.json() as any).state,'CLOSED');
  const records=await (await fetch(`${base}/api/research/results`,{headers:{Authorization:`Bearer ${token}`}})).json() as any;assert.equal(records.sessions.length,1);assert.equal(JSON.parse(records.sessions[0].consent).accepted,false);assert.equal(records.events.filter((e:any)=>e.type==='transcript').length,0);
 }finally{child.kill('SIGTERM');await new Promise<void>(resolve=>{if(child.exitCode!==null)resolve();else child.once('exit',()=>resolve());});}
});
test('browser startup failure remains a durable attempted run',async()=>{
 mkdirSync('.runtime/tests',{recursive:true});const dir=mkdtempSync(resolve('.runtime/tests/ledger-')),token='ledger-test-token';const child=spawn(process.execPath,['--import','tsx','src/server.ts','--demo'],{cwd:process.cwd(),env:{...process.env,DATA_PATH:`${dir}/test.sqlite`,RESEARCHER_TOKEN:token,CHROMIUM_PATH:'Z:\\missing\\chromium.exe'},stdio:['ignore','pipe','pipe']});let ws:WebSocket|undefined;
 try{await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('server_start_timeout')),5000);child.stdout.on('data',chunk=>{if(chunk.toString().includes('Ruang Akses:')){clearTimeout(timeout);resolve();}});child.on('exit',code=>{clearTimeout(timeout);reject(Error(`server exited ${code}`));});});const base='http://127.0.0.1:3050',created=await fetch(`${base}/api/sessions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'LEDGER',mode:'demo',slot:0,request_id:crypto.randomUUID()})}),session=await created.json() as any;await fetch(`${base}/api/consent`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.session_token}`},body:JSON.stringify({accepted:true,adult:true,version:'demo-v1',request_id:crypto.randomUUID()})});let envelope:any={session_id:session.session_id,run_id:null,epoch:0,goal_revision:0},state='CONSENT',readySent=false,nextSent=false;ws=new WebSocket('ws://127.0.0.1:3050/events',{headers:{Origin:'http://localhost:3050'}});ws.on('open',()=>ws!.send(JSON.stringify({type:'AUTH',token:session.session_token})));ws.on('message',raw=>{const m=JSON.parse(raw.toString());if(m.session_id){envelope={session_id:m.session_id,run_id:m.run_id,epoch:m.epoch,goal_revision:m.goal_revision,run_epoch:m.run_epoch};}if(m.type==='STATE')state=m.payload.state;const send=(type:string,extra:object={})=>ws!.send(JSON.stringify({...envelope,type,request_id:crypto.randomUUID(),...extra}));if(m.type==='PREPARE_PLAY')send('PLAY_READY',{turn_id:m.payload.id});if(m.type==='DEMO_TEXT')send('PLAYED',{turn_id:m.payload.id});if(m.type==='LISTEN'&&state==='READINESS'&&!readySent){readySent=true;send('TEXT',{text:'siap'});}else if(m.type==='LISTEN'&&state==='READY'&&!nextSent){nextSent=true;send('CONTROL',{command:'NEXT'});}});const end=Date.now()+10000;let records:any;do{await new Promise(r=>setTimeout(r,100));records=await (await fetch(`${base}/api/research/results`,{headers:{Authorization:`Bearer ${token}`}})).json();}while(!records.results.length&&Date.now()<end);assert.equal(records.runs.length,1);assert.equal(records.results.length,1);assert.equal(records.runs[0].id,records.results[0].run_id);assert.equal(records.results[0].agent_termination_reason,'infrastructure_failed');assert.equal(records.results[0].failure_category,'infrastructure_failure');assert.equal(records.results[0].final_task_status,'ABORTED');assert.equal(records.results[0].task_success,null);assert.equal(JSON.parse(records.runs[0].metadata).chromium,null);for(const type of ['TASK_START','INFRASTRUCTURE_FAILURE','ORACLE_CHECK','TASK_END'])assert.ok(records.events.some((e:any)=>e.type===type),type);
 }finally{ws?.close();child.kill('SIGTERM');await new Promise<void>(resolve=>{if(child.exitCode!==null)resolve();else child.once('exit',()=>resolve());});}
});
