import {test} from 'node:test';import assert from 'node:assert/strict';
import {fixtureHarness} from '../../src/fixture/harness.ts';import {makeScenario} from '../../src/fixture/dataset.ts';
import {openTask} from '../../src/browser/task-browser.ts';import {Observer} from '../../src/browser/observer.ts';
import {AgentRun} from '../../src/agent/run.ts';import {DemoModel} from '../../src/agent/demo-model.ts';
import {evaluateOutcome} from '../../src/evaluation/oracle.ts';
const until=async(predicate:()=>boolean,timeout=15000)=>{const end=Date.now()+timeout;while(!predicate()){if(Date.now()>end)throw Error('condition_timeout');await new Promise(r=>setTimeout(r,25));}};
test('real browser integration, with explicitly synthetic planner',async t=>{
 const h=await fixtureHarness();try{
  for(const presentation of ['EARLY','STAGED'] as const)for(const condition of ['P','B1'] as const)await t.test(`${condition}/${presentation} executes browser and verifies stored cart`,async()=>{
   const w=h.fixtures.create(makeScenario(0,'development',presentation));const task=await openTask(w.id,w.secret,()=>assert.fail('egress'),process.env.CHROMIUM_PATH);let result:any;const events:any[]=[];
   const run=new AgentRun(task.page,task.browser,task.server,condition,new DemoModel(),{log:(type,payload)=>events.push({type,payload}),status:()=>{},ask:()=>{},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},true,w.scenario.instruction);
   await run.input(w.scenario.instruction);await run.done;const expectedBudgetLimited=condition==='B1'&&presentation==='STAGED'&&result.agent_termination_reason==='budget_exhausted';assert.ok(result.agent_termination_reason==='verified_complete'||expectedBudgetLimited,JSON.stringify(result));assert.ok(result.counters.probes<=4);if(presentation==='EARLY')assert.equal(result.counters.probes,0);else{assert.ok(result.counters.routerComparisons>0);assert.ok(result.counters.firstFeasibleProbe===null||result.counters.firstFeasibleProbe>0);const probeModelCalls=events.filter(e=>e.type==='model_io'&&e.payload.input?.eligible_probes);assert.ok(probeModelCalls.every(e=>e.payload.input.eligible_probes.length>1));assert.equal(result.counters.routerComparisons,events.filter(e=>e.type==='planner_proposal'&&e.payload.router_comparison.comparable).length);}if(expectedBudgetLimited){assert.equal(result.oracle_success,false);assert.equal(w.cart.length,0);}else{assert.equal(result.verification_status,'PASS');assert.equal(result.oracle_success,true);assert.equal(w.cart.length,1);assert.equal(events.filter(e=>e.type==='action_intent'&&e.payload.expected.kind==='ADD_CART').length,1);}
  });
  await t.test('AC-10: replaced element never inherits old snapshot binding',async()=>{const w=h.fixtures.create(makeScenario(1));const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);try{const observer=new Observer(task.page);const o=await observer.observe();const control=o.controls.find(c=>c.kind==='OPEN_DETAIL')!;await task.page.getByRole('link',{name:control.exactName,exact:true}).evaluate(el=>el.replaceWith(el.cloneNode(true)));await assert.rejects(()=>observer.validate(control));}finally{await task.browser.close();await task.server.close();}});
  await t.test('AC-09: planner sees public list facts but not closed variant panels',async()=>{const w=h.fixtures.create(makeScenario(1));const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);try{const o=await new Observer(task.page).observe();assert.equal(o.facts.filter(f=>f.field==='material').length,3);assert.equal(o.facts.filter(f=>f.field!=='material').length,0);assert.ok(!o.snapshot.includes('Stok:'));assert.ok(!o.snapshot.includes('Harga varian:'));assert.ok(!o.snapshot.includes(w.scenario.base));}finally{await task.browser.close();await task.server.close();}});
  await t.test('no-solution is concluded only after three public refutations',async()=>{const w=h.fixtures.create(makeScenario(12,'main','STAGED'));const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);let result:any;const run=new AgentRun(task.page,task.browser,task.server,'P',new DemoModel(),{log:()=>{},status:()=>{},ask:()=>{},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},true,w.scenario.instruction);await run.input(w.scenario.instruction);await run.done;assert.equal(result.agent_termination_reason,'no_feasible_in_scope',JSON.stringify(result));assert.equal(result.public_refutations,true);assert.equal(result.feasible_exists,false);assert.equal(result.act_abstain_correct,true);assert.equal(result.probes_to_evidence_closure,4);assert.equal(result.excess_probe_cost,0);});
  await t.test('unavailable evidence ends honestly instead of exhausting the probe budget',async()=>{const w=h.fixtures.create(makeScenario(14,'main','STAGED'));const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);let result:any;const run=new AgentRun(task.page,task.browser,task.server,'P',new DemoModel(),{log:()=>{},status:()=>{},ask:()=>{},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},true,w.scenario.instruction);await run.input(w.scenario.instruction);await run.done;assert.equal(result.agent_termination_reason,'insufficient_evidence',JSON.stringify(result));assert.equal(result.act_abstain_correct,true);assert.equal(result.probes_to_evidence_closure,3);assert.equal(result.excess_probe_cost,0);assert.equal(w.cart.length,0);});
  await t.test('probe ceiling produces an explicit budget-limited outcome',async()=>{const scenario=makeScenario(0,'development','STAGED');for(const p of scenario.products)p.variants[0].exposePrice=false;scenario.referenceEvidence.minimumProbes=null;const w=h.fixtures.create(scenario);const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);let result:any;const run=new AgentRun(task.page,task.browser,task.server,'P',new DemoModel(),{log:()=>{},status:()=>{},ask:()=>{},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},true,w.scenario.instruction);await run.input(w.scenario.instruction);await run.done;assert.equal(result.agent_termination_reason,'budget_exhausted',JSON.stringify(result));assert.equal(result.counters.probes,4);assert.equal(result.probes_to_evidence_closure,null);assert.equal(w.cart.length,0);});
  await t.test('declining a proposal searches for another feasible candidate without side effects',async()=>{const w=h.fixtures.create(makeScenario(3,'development','EARLY'));const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);let result:any;const approvals:string[]=[];const run=new AgentRun(task.page,task.browser,task.server,'P',new DemoModel(),{log:()=>{},status:()=>{},ask:(_text,id)=>{if(id)approvals.push(id);},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},false,w.scenario.instruction);await run.input(w.scenario.instruction);await until(()=>run.phase==='AWAITING_APPROVAL',30000);assert.equal(w.cart.length,0);assert.equal(run.rejectProposal(),true);await until(()=>approvals.length===2&&run.phase==='AWAITING_APPROVAL',30000);assert.equal(w.cart.length,0);await run.approve(approvals[1]);await run.done;assert.equal(result.oracle_success,true,JSON.stringify(result));assert.equal(w.cart.length,1);});
  await t.test('false success toast cannot pass stored-cart verification',async()=>{const w=h.fixtures.create(makeScenario(0,'development','EARLY'),'false-toast');const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);let result:any;const run=new AgentRun(task.page,task.browser,task.server,'P',new DemoModel(),{log:()=>{},status:()=>{},ask:()=>{},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},true,w.scenario.instruction);await run.input(w.scenario.instruction);await run.done;assert.equal(result.agent_termination_reason,'execution_failed');assert.equal(result.verification_status,'FAIL');assert.equal(result.oracle_success,false);assert.equal(w.cart.length,0);});
  await t.test('independent oracle detects a deliberately deceptive cart rendering',async()=>{const w=h.fixtures.create(makeScenario(0,'development','EARLY'),'fake-cart');const task=await openTask(w.id,w.secret,()=>{},process.env.CHROMIUM_PATH);let result:any;const run=new AgentRun(task.page,task.browser,task.server,'P',new DemoModel(),{log:()=>{},status:()=>{},ask:()=>{},finished:async(outcome,quiescent)=>{w.closed=true;result={...outcome,...evaluateOutcome(w,outcome,quiescent)};}},true,w.scenario.instruction);await run.input(w.scenario.instruction);await run.done;assert.equal(result.agent_claimed_success,true);assert.equal(result.oracle_success,false);assert.equal(result.oracle_assessment_reason,'empty_cart');});
 }finally{await h.close();}
});
