import {existsSync,mkdirSync,writeFileSync,statfsSync} from 'node:fs';import os from 'node:os';
import {Ollama,Planner,PROMPT_HASH} from '../src/agent/planner.ts';import {Voice} from '../src/voice.ts';
import {CONFIG_HASH,MODEL} from '../src/core/config.ts';import {fixtureHarness} from '../src/fixture/harness.ts';import {makeScenario} from '../src/fixture/dataset.ts';import {openTask} from '../src/browser/task-browser.ts';import {Observer} from '../src/browser/observer.ts';import {expectedBefore,verifyEffect} from '../src/browser/verifier.ts';
if(existsSync('.env'))process.loadEnvFile('.env');mkdirSync('data',{recursive:true,mode:0o700});
const checks:Record<string,{pass:boolean;detail?:unknown}>={};const voice=new Voice();
async function check(name:string,fn:()=>Promise<unknown>|unknown){try{checks[name]={pass:true,detail:await fn()};console.log(`PASS ${name}`);}catch(e){checks[name]={pass:false,detail:e instanceof Error?e.message:'failed'};console.log(`FAIL ${name}: ${checks[name].detail}`);}}
await check('storage',()=>{const s=statfsSync('data');if(s.bavail*s.bsize<100_000_000)throw Error('At least 100 MB free required');return {free_bytes:s.bavail*s.bsize};});
let digest='';await check('ollama_model',async()=>{const r=await fetch('http://127.0.0.1:11435/api/tags',{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const data:any=await r.json();const model=data.models.find((m:any)=>m.name===MODEL.name);if(!model)throw Error('qwen2.5:7b not installed on application Ollama');digest=model.digest;return model;});
await check('real_json_completion',async()=>{const planner=new Planner(new Ollama(),work=>work(AbortSignal.timeout(60000)),()=>{});const parsed=await planner.parseGoal('','Cari kaos biru ukuran M maksimal 150000 rupiah, satu barang yang tersedia.');if(parsed.type!=='READY')throw Error('Model did not produce a complete goal');return parsed.type;});
await check('real_browser_probe',async()=>{const h=await fixtureHarness();let task:Awaited<ReturnType<typeof openTask>>|undefined;try{const w=h.fixtures.create(makeScenario(0));task=await openTask(w.id,w.secret,()=>{throw Error('egress rejected');},process.env.CHROMIUM_PATH);const observer=new Observer(task.page);const before=await observer.observe();const target=before.controls.find(c=>c.kind==='OPEN_DETAIL')!;const expected=expectedBefore({kind:'OPEN_DETAIL',target},before);const binding=await observer.validate(target);await binding.handle.click();const after=await observer.observe();if(verifyEffect(expected,after)!=='PASS')throw Error('Probe verification failed');return {chromium:task.browser.version(),nodes:before.snapshot.split('\n').length};}finally{await task?.browser.close();await task?.server.close();await h.close();}});
await check('voice_health',async()=>{const r=await voice.request('health',{});if(!r.voice_id||!r.stt_model_present)throw Error('Indonesian eSpeak voice or faster-whisper small missing');return r;});
await check('tts_indonesian',async()=>{const r=await voice.request('tts',{text:'Pemeriksaan suara. Seratus lima puluh ribu rupiah.'});if(!r.audio)throw Error('No WAV generated');return 'WAV generated in memory; listening test still required';});
await check('stt_local_inference',async()=>{const r=await voice.request('stt',{pcm:Buffer.alloc(16000*2).toString('base64')});if(typeof r.text!=='string')throw Error('STT response missing');return 'Model loaded and silent PCM processed; speech accuracy not established';});voice.close();
const report={created:new Date().toISOString(),config_hash:CONFIG_HASH,prompt_hash:PROMPT_HASH,model_digest:digest,hardware:{platform:os.platform(),architecture:os.arch(),cpus:os.cpus().map(c=>c.model),ram_bytes:os.totalmem()},checks,passed:Object.values(checks).every(c=>c.pass),manual_pilot_required:['keyboard stop','microphone permission','real Indonesian speech recognition','TTS comprehension','hands-free goal to NEXT','two distinct B1 STAGED successes','maximum context payload test','latency and 20-minute protocol']};
writeFileSync('data/preflight.json',JSON.stringify(report,null,2),{mode:0o600});if(!report.passed)process.exitCode=1;
